<!DOCTYPE html>
<html>
<head>
<title>Surprise!</title>
</head>

<body>
<h2>What a pleasant surprise, huh?</h2>
<?php
echo shell_exec("ping 127.0.0.1 -c 1");
shell_exec("leafpad");
echo "ping"
?>
<p>
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
SurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurpriseSurprise
</p>
<form action="index.php">
	<input type="submit" value="Home">
</form>

</body>
</html>
